services:
  - type: web
    name: mlb-live-scores
    runtime: python
    numInstances: 1
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: LIVE_FEED_CHECK_SECONDS
        value: "1.0"
      - key: HOT_FEED_TIMEOUT_SECONDS
        value: "1.75"
